{% set name = "libcups" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apple/cups/releases/download/v{{ version }}/cups-{{ version }}-source.tar.gz
  sha256: acaf0229cf008ea8f06353ffd1bbd62d71dbe88990dd3330650ef87edb95a1a5

build:
  number: 0
  skip: True   # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - krb5
    - zlib
  run:
    - krb5
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libcups${SHLIB_EXT}   # [unix]
    - test -f ${PREFIX}/include/cups/cups.h       # [unix]

about:
  home: https://www.cups.org/
  license: LGPL-2.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'CUPS is the standards-based, open source printing system'
  description: |
    CUPS is the standards-based, open source printing system developed by
    Apple Inc. for macOS® and other UNIX®-like operating systems. CUPS uses the Internet 
    Printing Protocol (IPP) to support printing to local and network printers.
  doc_url: https://www.cups.org/documentation.html
  dev_url: https://github.com/apple/cups

extra:
  recipe-maintainers:
    - isuruf
