{% set name = "libcups" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apple/cups/releases/download/v{{ version }}/cups-{{ version }}-source.tar.gz
  sha256: 261fd948bce8647b6d5cb2a1784f0c24cc52b5c4e827b71d726020bcc502f3ee

build:
  number: 4
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('libcups', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - krb5
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libcups${SHLIB_EXT}   # [unix]
    - test -f ${PREFIX}/include/cups/cups.h       # [unix]

about:
  home: https://www.cups.org/
  license:  Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: CUPS is the standards-based, open source printing system
  description: |
    CUPS is the standards-based, open source printing system developed by
    Apple Inc. for macOS® and other UNIX®-like operating systems. CUPS uses the Internet 
    Printing Protocol (IPP) to support printing to local and network printers.
  doc_url: https://www.cups.org/documentation.html
  dev_url: https://github.com/apple/cups

extra:
  recipe-maintainers:
    - isuruf
    - hmaarrfk
